// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3BwSAKmzKZAWesPKzvAS1a
// Component: 0LevCU4qTT
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_sana.module.css"; // plasmic-import: 3BwSAKmzKZAWesPKzvAS1a/projectcss
import * as sty from "./PlasmicMyApp.module.css"; // plasmic-import: 0LevCU4qTT/css

export const PlasmicMyApp__VariantProps = new Array();

export const PlasmicMyApp__ArgProps = new Array();

function PlasmicMyApp__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMyApp__ArgProps,
      internalVariantPropNames: PlasmicMyApp__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicMyApp__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMyApp";
  } else {
    func.displayName = `PlasmicMyApp.${nodeName}`;
  }
  return func;
}

export const PlasmicMyApp = Object.assign(
  // Top-level PlasmicMyApp renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicMyApp
    internalVariantProps: PlasmicMyApp__VariantProps,
    internalArgProps: PlasmicMyApp__ArgProps
  }
);

export default PlasmicMyApp;
/* prettier-ignore-end */
