// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicHomepage } from "./plasmic/sana/PlasmicHomepage";


function Homepage_(props, ref) {
  
  return (
    
      <PlasmicHomepage root={{ ref }} {...props} />
      
  );
}

const Homepage = React.forwardRef(Homepage_);

export default Homepage;
